# Introduction

In [ ]:
import tensorflow as tf
tf.compat.v1.enable_eager_execution()

import numpy as np

In [ ]:
x = tf.constant(11)
y = tf.constant(11)
z = x*y
print(z)

tf.Tensor(121, shape=(), dtype=int32)


In [ ]:
z.numpy()

np.int32(121)

In [ ]:
np.int32(121)

np.int32(121)

In [ ]:
x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

In [ ]:
sum = tf.add(x,y)
sum.numpy()

array([4., 4., 4.], dtype=float32)

In [ ]:
difference = tf.subtract(x,y)
difference.numpy()

array([-2.,  0.,  2.], dtype=float32)

In [ ]:
product = tf.multiply(x,y)
product.numpy()

array([3., 4., 3.], dtype=float32)

In [ ]:
division = tf.divide(x,y)
division.numpy()

array([0.33333334, 1.        , 3.        ], dtype=float32)

In [ ]:
dot_product = tf.reduce_sum(tf.multiply(x, y))
dot_product.numpy()

np.float32(10.0)

In [ ]:
x = tf.constant([10, 0, 13, 9])
print(tf.argmin(x).numpy())
print(tf.argmax(x).numpy())

1
2


In [ ]:
x = tf.Variable([1,3,5,7,11])
y = tf.Variable([1])
tf.math.squared_difference(x,y).numpy()

array([  0,   4,  16,  36, 100], dtype=int32)

In [ ]:
print(x.dtype)

<dtype: 'int32'>


In [ ]:
x = tf.cast(x, dtype=tf.float32)
print(x.dtype)

<dtype: 'float32'>


In [ ]:
x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]

In [ ]:
tf.concat([x, y], 0).numpy()

array([[3, 6, 9],
       [7, 7, 7],
       [4, 5, 6],
       [5, 5, 5]], dtype=int32)

In [ ]:
tf.concat([x, y], 1).numpy()

array([[3, 6, 9, 4, 5, 6],
       [7, 7, 7, 5, 5, 5]], dtype=int32)

In [ ]:
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

In [ ]:
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

In [ ]:
tf.reduce_mean(input_tensor=x).numpy()

np.float32(2.75)

In [ ]:
tf.reduce_mean(input_tensor=x, axis=1, keepdims=True).numpy()

array([[3. ],
       [2.5]], dtype=float32)

In [ ]:
tf.random.normal(shape=(3,2), mean=10.0, stddev=2.0).numpy()
tf.random.uniform(shape = (3,2), minval=0, maxval=None, dtype=tf.float32,).numpy()

array([[0.7636068 , 0.7748405 ],
       [0.2169689 , 0.907037  ],
       [0.01039052, 0.04166198]], dtype=float32)

In [ ]:
x = tf.constant([7., 2., 5.])
tf.nn.softmax(x).numpy()

array([0.8756006 , 0.00589975, 0.11849965], dtype=float32)

In [ ]:
def square(x):
  return tf.multiply(x, x)

In [ ]:
with tf.GradientTape(persistent=True) as tape:
  print(square(6.).numpy())

36.0


# TensorFlow 2.0 and Keras

In [ ]:
from tensorflow import keras

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(13, input_dim=7, activation='relu'))
model.add(Dense(7, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
input = tf.keras.Input(shape=(2,))
layer1 = Dense(10, activation='relu')(input)
layer2 = Dense(10, activation='relu')(layer1)
output = Dense(1, activation='sigmoid')(layer2)
model = tf.keras.Model(inputs=input, outputs=output)

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [ ]:
mnist = tf.keras.datasets.mnist

In [ ]:
(x_train,y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
x_train, x_test = tf.cast(x_train/255.0, tf.float32), tf.cast(x_test/255.0, tf.float32)
y_train, y_test = tf.cast(y_train,tf.int64),tf.cast(y_test,tf.int64)

In [ ]:
model = tf.keras.models.Sequential()

In [ ]:
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(256, activation="relu"))
model.add(tf.keras.layers.Dense(128, activation="relu"))
model.add(tf.keras.layers.Dense(10, activation="softmax"))

In [ ]:
model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, batch_size=32, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.1425 - loss: 2.2896
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.3449 - loss: 1.7869
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.5066 - loss: 1.1381
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.7121 - loss: 0.8025
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.8233 - loss: 0.5456
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9088 - loss: 0.3682
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9405 - loss: 0.2540
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9552 - loss: 0.1836
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9640 - loss: 0.1423
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - accuracy: 0.9712 - loss: 0.1139


In [ ]:
model.evaluate(x_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9345 - loss: 0.2564


[0.22409474849700928, 0.9447000026702881]